"""
Seed script: llena la tabla properties con 25 propiedades ficticias
para el broker "Inmobiliaria Santiago Centro" (slug: santiago-centro).

Idempotente — omite propiedades que ya tengan el mismo codigo.

Uso (dentro de Docker):
    docker compose exec backend python scripts/seed_properties.py

Uso (local con venv):
    cd backend && .venv/bin/python scripts/seed_properties.py
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from sqlalchemy import select

from app.config import settings
from app.models.broker import Broker
from app.models.property import Property

# ──────────────────────────────────────────────────────────────────────────────
# Datos ficticios
# ──────────────────────────────────────────────────────────────────────────────

PROPERTIES = [
    # ── Departamentos Santiago Centro ─────────────────────────────────────────
    {
        "codigo": "SC-001",
        "name": "Departamento Luminoso en Lastarria",
        "property_type": "departamento",
        "status": "available",
        "commune": "Santiago",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Italia 234, piso 5, Santiago",
        "latitude": -33.4378,
        "longitude": -70.6327,
        "price_uf": 3200.0,
        "price_clp": 115_200_000,
        "bedrooms": 2,
        "bathrooms": 1,
        "parking_spots": 0,
        "storage_units": 1,
        "square_meters_total": 58.0,
        "square_meters_useful": 52.0,
        "floor_number": 5,
        "total_floors": 12,
        "orientation": "nororiente",
        "year_built": 2018,
        "description": "Hermoso departamento en pleno barrio Lastarria. Amplio living-comedor con vista despejada al cerro Santa Lucía. Cocina equipada con muebles de melamina. Dormitorios con clóset. Edificio con portería 24/7.",
        "highlights": "Vista al cerro, luminoso, barrio bohemio, cerca del metro Baquedano",
        "amenities": ["gimnasio", "roof_garden", "bicicletero", "lavandería_común"],
        "nearby_places": [
            {"type": "metro", "name": "Baquedano", "distance_m": 350},
            {"type": "parque", "name": "Cerro Santa Lucía", "distance_m": 400},
            {"type": "supermercado", "name": "Unimarc Italia", "distance_m": 200},
        ],
        "financing_options": ["crédito_hipotecario", "pie_en_cuotas"],
        "common_expenses_clp": 45_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-002",
        "name": "Estudio Moderno Barrio República",
        "property_type": "departamento",
        "status": "available",
        "commune": "Santiago",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. República 891, piso 3, Santiago",
        "latitude": -33.4512,
        "longitude": -70.6578,
        "price_uf": 1850.0,
        "price_clp": 66_600_000,
        "bedrooms": 1,
        "bathrooms": 1,
        "parking_spots": 0,
        "storage_units": 0,
        "square_meters_total": 32.0,
        "square_meters_useful": 29.0,
        "floor_number": 3,
        "total_floors": 8,
        "orientation": "sur",
        "year_built": 2020,
        "description": "Estudio compacto y moderno ideal para profesionales o estudiantes. Cocina americana integrada al living. Baño completo con ducha. Excelente conectividad con el centro de Santiago.",
        "highlights": "Precio accesible, céntrico, ideal primera vivienda",
        "amenities": ["bicicletero", "sala_multiuso"],
        "nearby_places": [
            {"type": "metro", "name": "República", "distance_m": 180},
            {"type": "universidad", "name": "U. de Santiago", "distance_m": 600},
        ],
        "financing_options": ["crédito_hipotecario", "subsidio_DS19"],
        "common_expenses_clp": 28_000,
        "subsidio_eligible": True,
    },
    {
        "codigo": "SC-003",
        "name": "Departamento 3D+2B con Terraza Barrio Italia",
        "property_type": "departamento",
        "status": "available",
        "commune": "Providencia",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Condell 1560, piso 8, Providencia",
        "latitude": -33.4355,
        "longitude": -70.6289,
        "price_uf": 5800.0,
        "price_clp": 208_800_000,
        "bedrooms": 3,
        "bathrooms": 2,
        "parking_spots": 1,
        "storage_units": 1,
        "square_meters_total": 92.0,
        "square_meters_useful": 84.0,
        "floor_number": 8,
        "total_floors": 14,
        "orientation": "norte",
        "year_built": 2019,
        "description": "Espacioso departamento con terraza privada de 12 m² en pleno barrio Italia. Living con piso de madera, dormitorio principal con baño en suite. Cocina abierta con isla. Estacionamiento incluido.",
        "highlights": "Terraza privada, dormitorio en suite, barrio Italia, excelente calidad de construcción",
        "amenities": ["piscina", "gimnasio", "quincho", "salón_eventos", "bicicletero"],
        "nearby_places": [
            {"type": "metro", "name": "Ñuñoa", "distance_m": 500},
            {"type": "parque", "name": "Parque Bustamante", "distance_m": 650},
            {"type": "feria", "name": "Feria Barrio Italia", "distance_m": 300},
        ],
        "financing_options": ["crédito_hipotecario", "pie_en_cuotas"],
        "common_expenses_clp": 85_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-004",
        "name": "Departamento 2D con Vista Panorámica Las Condes",
        "property_type": "departamento",
        "status": "available",
        "commune": "Las Condes",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Apoquindo 3900, piso 15, Las Condes",
        "latitude": -33.4166,
        "longitude": -70.5978,
        "price_uf": 7200.0,
        "price_clp": 259_200_000,
        "bedrooms": 2,
        "bathrooms": 2,
        "parking_spots": 1,
        "storage_units": 1,
        "square_meters_total": 78.0,
        "square_meters_useful": 71.0,
        "floor_number": 15,
        "total_floors": 22,
        "orientation": "nororiente",
        "year_built": 2021,
        "description": "Departamento de alta gama con vista panorámica a la cordillera. Terminaciones premium, piso de porcelanato, ventanas termopanel. Edificio con lobby de lujo, portero 24/7 y cámaras de seguridad.",
        "highlights": "Vista cordillera, piso alto, terminaciones premium, sector financiero",
        "amenities": ["piscina", "gimnasio", "spa", "salón_eventos", "estacionamiento_visitas"],
        "nearby_places": [
            {"type": "metro", "name": "Escuela Militar", "distance_m": 400},
            {"type": "mall", "name": "Parque Arauco", "distance_m": 800},
            {"type": "supermercado", "name": "Jumbo Kennedy", "distance_m": 350},
        ],
        "financing_options": ["crédito_hipotecario"],
        "common_expenses_clp": 120_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-005",
        "name": "Departamento Económico Subsidio Pudahuel",
        "property_type": "departamento",
        "status": "available",
        "commune": "Pudahuel",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Calle Los Aromos 456, Pudahuel",
        "latitude": -33.4456,
        "longitude": -70.7589,
        "price_uf": 1200.0,
        "price_clp": 43_200_000,
        "bedrooms": 2,
        "bathrooms": 1,
        "parking_spots": 0,
        "storage_units": 0,
        "square_meters_total": 45.0,
        "square_meters_useful": 42.0,
        "floor_number": 2,
        "total_floors": 4,
        "orientation": "oriente",
        "year_built": 2022,
        "description": "Departamento nuevo con subsidio habitacional disponible. Entrega inmediata. Cocina con muebles básicos, dormitorios con clóset empotrado. Condominio cerrado con área de juegos infantiles.",
        "highlights": "Subsidio disponible, entrega inmediata, condominio cerrado",
        "amenities": ["área_verde", "juegos_infantiles", "estacionamiento_visitas"],
        "nearby_places": [
            {"type": "colegio", "name": "Escuela Municipal Pudahuel", "distance_m": 400},
            {"type": "supermercado", "name": "Lider Pudahuel", "distance_m": 700},
        ],
        "financing_options": ["crédito_hipotecario", "subsidio_DS49", "subsidio_DS19"],
        "common_expenses_clp": 18_000,
        "subsidio_eligible": True,
    },
    # ── Casas ─────────────────────────────────────────────────────────────────
    {
        "codigo": "SC-006",
        "name": "Casa Moderna con Piscina La Florida",
        "property_type": "casa",
        "status": "available",
        "commune": "La Florida",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Calle Las Rosas 2341, La Florida",
        "latitude": -33.5123,
        "longitude": -70.5934,
        "price_uf": 9500.0,
        "price_clp": 342_000_000,
        "bedrooms": 4,
        "bathrooms": 3,
        "parking_spots": 2,
        "storage_units": 1,
        "square_meters_total": 185.0,
        "square_meters_useful": 160.0,
        "floor_number": None,
        "total_floors": 2,
        "orientation": "norte",
        "year_built": 2016,
        "description": "Hermosa casa de dos pisos en condominio cerrado. Amplio jardín con piscina y quincho. Primer piso: living-comedor, cocina americana, dormitorio de servicio y baño. Segundo piso: 3 dormitorios, 2 baños. Alarma y CCTV.",
        "highlights": "Piscina propia, quincho, jardín, condominio cerrado, 2 estacionamientos",
        "amenities": ["piscina", "quincho", "jardín", "alarma", "doble_estacionamiento"],
        "nearby_places": [
            {"type": "metro", "name": "Protectora de la Infancia", "distance_m": 600},
            {"type": "mall", "name": "Plaza Vespucio", "distance_m": 1200},
            {"type": "colegio", "name": "Colegio La Florida", "distance_m": 400},
        ],
        "financing_options": ["crédito_hipotecario", "pie_en_cuotas"],
        "common_expenses_clp": 55_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-007",
        "name": "Casa Familiar Ñuñoa 3 Dormitorios",
        "property_type": "casa",
        "status": "available",
        "commune": "Ñuñoa",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Irarrázaval 4502, Ñuñoa",
        "latitude": -33.4612,
        "longitude": -70.6089,
        "price_uf": 8200.0,
        "price_clp": 295_200_000,
        "bedrooms": 3,
        "bathrooms": 2,
        "parking_spots": 1,
        "storage_units": 0,
        "square_meters_total": 130.0,
        "square_meters_useful": 118.0,
        "floor_number": None,
        "total_floors": 2,
        "orientation": "norte",
        "year_built": 2008,
        "description": "Casa de dos plantas en barrio tranquilo de Ñuñoa. Primer piso con living, comedor, cocina y patio. Segundo piso con 3 dormitorios y 2 baños. Remodelada el 2023 con nueva cocina y baños.",
        "highlights": "Barrio tranquilo, remodelada, cerca del metro, patio con parrilla",
        "amenities": ["patio", "parrilla", "bodega"],
        "nearby_places": [
            {"type": "metro", "name": "Ñuñoa", "distance_m": 450},
            {"type": "parque", "name": "Estadio Nacional", "distance_m": 800},
            {"type": "supermercado", "name": "Tottus Irarrázaval", "distance_m": 300},
        ],
        "financing_options": ["crédito_hipotecario"],
        "common_expenses_clp": 0,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-008",
        "name": "Casa con Subsidio DS19 Maipú",
        "property_type": "casa",
        "status": "available",
        "commune": "Maipú",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Calle El Roble 789, Maipú",
        "latitude": -33.5178,
        "longitude": -70.7623,
        "price_uf": 2100.0,
        "price_clp": 75_600_000,
        "bedrooms": 3,
        "bathrooms": 2,
        "parking_spots": 1,
        "storage_units": 0,
        "square_meters_total": 68.0,
        "square_meters_useful": 63.0,
        "floor_number": None,
        "total_floors": 1,
        "orientation": "oriente",
        "year_built": 2023,
        "description": "Casa nueva en condominio con subsidio DS19 disponible. Diseño moderno, cocina integrada al living. Patio trasero. Estacionamiento techado. Condominio con portería y cámaras.",
        "highlights": "Casa nueva, subsidio DS19, condominio seguro, Maipú",
        "amenities": ["patio", "estacionamiento_techado", "portería"],
        "nearby_places": [
            {"type": "metro", "name": "Del Sol", "distance_m": 500},
            {"type": "mall", "name": "Mall Plaza Maipú", "distance_m": 1500},
        ],
        "financing_options": ["crédito_hipotecario", "subsidio_DS19"],
        "common_expenses_clp": 22_000,
        "subsidio_eligible": True,
    },
    {
        "codigo": "SC-009",
        "name": "Casa de Lujo con Vista Cordillera Lo Barnechea",
        "property_type": "casa",
        "status": "available",
        "commune": "Lo Barnechea",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Camino El Alba 11200, Lo Barnechea",
        "latitude": -33.3578,
        "longitude": -70.5145,
        "price_uf": 28000.0,
        "price_clp": 1_008_000_000,
        "bedrooms": 5,
        "bathrooms": 4,
        "parking_spots": 3,
        "storage_units": 2,
        "square_meters_total": 380.0,
        "square_meters_useful": 340.0,
        "floor_number": None,
        "total_floors": 2,
        "orientation": "norte",
        "year_built": 2017,
        "description": "Espectacular casa de lujo en sector exclusivo de Lo Barnechea. Vista despejada a la cordillera. Sala de cine, bodega de vinos, piscina temperada. Terminaciones de primera línea: pisos de madera importada, cocina de chef.",
        "highlights": "Vista cordillera, piscina temperada, sala de cine, barrio exclusivo",
        "amenities": ["piscina_temperada", "quincho", "sala_cine", "bodega_vinos", "jardín_paisajístico", "alarma_central"],
        "nearby_places": [
            {"type": "colegio", "name": "The Grange School", "distance_m": 2000},
            {"type": "club", "name": "Club de Golf Los Leones", "distance_m": 3000},
        ],
        "financing_options": ["crédito_hipotecario"],
        "common_expenses_clp": 180_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-010",
        "name": "Casa Pareada Pudahuel Norte",
        "property_type": "casa",
        "status": "available",
        "commune": "Pudahuel",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Pasaje Los Olmos 23, Pudahuel Norte",
        "latitude": -33.4012,
        "longitude": -70.7812,
        "price_uf": 1650.0,
        "price_clp": 59_400_000,
        "bedrooms": 3,
        "bathrooms": 1,
        "parking_spots": 1,
        "storage_units": 0,
        "square_meters_total": 55.0,
        "square_meters_useful": 50.0,
        "floor_number": None,
        "total_floors": 1,
        "orientation": "sur",
        "year_built": 2015,
        "description": "Casa pareada en sector residencial tranquilo. Living-comedor, cocina independiente, 3 dormitorios y baño completo. Patio frontal y trasero. Estacionamiento descubierto. Postulable a subsidio.",
        "highlights": "Subsidio disponible, patio, sector tranquilo",
        "amenities": ["patio", "estacionamiento"],
        "nearby_places": [
            {"type": "colegio", "name": "Escuela Arturo Prat", "distance_m": 300},
            {"type": "supermercado", "name": "Ekono Pudahuel", "distance_m": 600},
        ],
        "financing_options": ["crédito_hipotecario", "subsidio_DS49"],
        "common_expenses_clp": 0,
        "subsidio_eligible": True,
    },
    # ── Más departamentos variados ─────────────────────────────────────────────
    {
        "codigo": "SC-011",
        "name": "Departamento 1D+1B Estación Central",
        "property_type": "departamento",
        "status": "available",
        "commune": "Estación Central",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Alameda 3200, piso 6, Estación Central",
        "latitude": -33.4589,
        "longitude": -70.6845,
        "price_uf": 1650.0,
        "price_clp": 59_400_000,
        "bedrooms": 1,
        "bathrooms": 1,
        "parking_spots": 0,
        "storage_units": 1,
        "square_meters_total": 35.0,
        "square_meters_useful": 33.0,
        "floor_number": 6,
        "total_floors": 10,
        "orientation": "norte",
        "year_built": 2019,
        "description": "Práctico departamento de 1 dormitorio en Av. Alameda. Ideal para arrendar o como inversión. Edificio con sala de reuniones y lavandería. Excelente acceso a transporte público.",
        "highlights": "Ideal inversión, sobre Alameda, bodega incluida",
        "amenities": ["lavandería_común", "sala_reuniones", "bicicletero"],
        "nearby_places": [
            {"type": "metro", "name": "Estación Central", "distance_m": 250},
            {"type": "terminal", "name": "Alameda", "distance_m": 400},
        ],
        "financing_options": ["crédito_hipotecario", "subsidio_DS19"],
        "common_expenses_clp": 32_000,
        "subsidio_eligible": True,
    },
    {
        "codigo": "SC-012",
        "name": "Departamento 2D Vista al Mar Viña del Mar",
        "property_type": "departamento",
        "status": "available",
        "commune": "Viña del Mar",
        "city": "Viña del Mar",
        "region": "Región de Valparaíso",
        "address": "Av. Marina 245, piso 10, Viña del Mar",
        "latitude": -33.0153,
        "longitude": -71.5507,
        "price_uf": 4800.0,
        "price_clp": 172_800_000,
        "bedrooms": 2,
        "bathrooms": 2,
        "parking_spots": 1,
        "storage_units": 1,
        "square_meters_total": 72.0,
        "square_meters_useful": 65.0,
        "floor_number": 10,
        "total_floors": 18,
        "orientation": "poniente",
        "year_built": 2017,
        "description": "Espectacular departamento con vista al mar en Viña del Mar. Amplio balcón orientado al Pacífico. Living-comedor integrado con cocina americana. Edificio frente al borde costero.",
        "highlights": "Vista al mar, balcón, primera línea costera, Viña del Mar",
        "amenities": ["piscina", "gimnasio", "salón_eventos", "estacionamiento_visitas"],
        "nearby_places": [
            {"type": "playa", "name": "Playa de Viña", "distance_m": 50},
            {"type": "casino", "name": "Casino Municipal", "distance_m": 600},
        ],
        "financing_options": ["crédito_hipotecario", "pie_en_cuotas"],
        "common_expenses_clp": 95_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-013",
        "name": "Departamento Penthouse Vitacura",
        "property_type": "departamento",
        "status": "available",
        "commune": "Vitacura",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Vitacura 3400, piso 20, Vitacura",
        "latitude": -33.3956,
        "longitude": -70.5867,
        "price_uf": 18000.0,
        "price_clp": 648_000_000,
        "bedrooms": 4,
        "bathrooms": 3,
        "parking_spots": 2,
        "storage_units": 2,
        "square_meters_total": 240.0,
        "square_meters_useful": 215.0,
        "floor_number": 20,
        "total_floors": 20,
        "orientation": "norte",
        "year_built": 2020,
        "description": "Exclusivo penthouse en Vitacura con terraza de 80 m² y jacuzzi exterior. Vista 360° a la cordillera y la ciudad. Terminaciones de lujo, cocina de chef, home office. Doble estacionamiento y 2 bodegas.",
        "highlights": "Penthouse, terraza 80m², jacuzzi, vista 360°, Vitacura exclusivo",
        "amenities": ["jacuzzi_terraza", "piscina", "gimnasio", "concierge_24h", "spa", "sala_cine"],
        "nearby_places": [
            {"type": "mall", "name": "Vitacura Shopping", "distance_m": 300},
            {"type": "restaurante", "name": "Zona Gastronómica Vitacura", "distance_m": 400},
        ],
        "financing_options": ["crédito_hipotecario"],
        "common_expenses_clp": 320_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-014",
        "name": "Departamento 3D Peñalolén con Estacionamiento",
        "property_type": "departamento",
        "status": "available",
        "commune": "Peñalolén",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Tobalaba 9500, piso 4, Peñalolén",
        "latitude": -33.4812,
        "longitude": -70.5423,
        "price_uf": 4200.0,
        "price_clp": 151_200_000,
        "bedrooms": 3,
        "bathrooms": 2,
        "parking_spots": 1,
        "storage_units": 1,
        "square_meters_total": 80.0,
        "square_meters_useful": 73.0,
        "floor_number": 4,
        "total_floors": 8,
        "orientation": "oriente",
        "year_built": 2016,
        "description": "Amplio departamento familiar en sector residencial tranquilo de Peñalolén. 3 dormitorios con clósets, 2 baños completos, living-comedor amplio. Cocina con granito. Vista a los cerros.",
        "highlights": "Amplio, sector tranquilo, vista a los cerros, estacionamiento",
        "amenities": ["piscina", "área_verde", "juegos_infantiles", "sala_multiuso"],
        "nearby_places": [
            {"type": "supermercado", "name": "Jumbo Tobalaba", "distance_m": 800},
            {"type": "parque", "name": "Parque Peñalolén", "distance_m": 500},
        ],
        "financing_options": ["crédito_hipotecario", "pie_en_cuotas"],
        "common_expenses_clp": 65_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-015",
        "name": "Departamento Subsidio DS49 Quilicura",
        "property_type": "departamento",
        "status": "available",
        "commune": "Quilicura",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. General San Martín 4200, Quilicura",
        "latitude": -33.3612,
        "longitude": -70.7234,
        "price_uf": 950.0,
        "price_clp": 34_200_000,
        "bedrooms": 2,
        "bathrooms": 1,
        "parking_spots": 0,
        "storage_units": 0,
        "square_meters_total": 42.0,
        "square_meters_useful": 39.0,
        "floor_number": 1,
        "total_floors": 5,
        "orientation": "norte",
        "year_built": 2021,
        "description": "Departamento de interés social con subsidio DS49. Proyecto nuevo en Quilicura. 2 dormitorios y baño completo. Cocina independiente. Condominio con áreas verdes y juegos infantiles.",
        "highlights": "Subsidio DS49, proyecto nuevo, condominio familiar",
        "amenities": ["área_verde", "juegos_infantiles"],
        "nearby_places": [
            {"type": "colegio", "name": "Escuela Quilicura", "distance_m": 350},
            {"type": "supermercado", "name": "Ekono Quilicura", "distance_m": 500},
        ],
        "financing_options": ["subsidio_DS49", "crédito_hipotecario"],
        "common_expenses_clp": 15_000,
        "subsidio_eligible": True,
    },
    # ── Oficinas ──────────────────────────────────────────────────────────────
    {
        "codigo": "SC-016",
        "name": "Oficina Providencia 80 m²",
        "property_type": "oficina",
        "status": "available",
        "commune": "Providencia",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Nueva Providencia 1980, piso 7, Providencia",
        "latitude": -33.4289,
        "longitude": -70.6178,
        "price_uf": 5500.0,
        "price_clp": 198_000_000,
        "bedrooms": 0,
        "bathrooms": 2,
        "parking_spots": 2,
        "storage_units": 0,
        "square_meters_total": 85.0,
        "square_meters_useful": 80.0,
        "floor_number": 7,
        "total_floors": 12,
        "orientation": "norte",
        "year_built": 2014,
        "description": "Oficina lista para usar en edificio clase A de Providencia. Open space con sala de reuniones privada. Dos baños y kitchenette. 2 estacionamientos en subterráneo. Edificio con generador de respaldo.",
        "highlights": "Edificio clase A, llave en mano, 2 estacionamientos, Providencia",
        "amenities": ["sala_reuniones", "kitchenette", "generador", "estacionamiento_subterráneo"],
        "nearby_places": [
            {"type": "metro", "name": "Pedro de Valdivia", "distance_m": 300},
            {"type": "restaurante", "name": "Zona gastronómica Providencia", "distance_m": 200},
        ],
        "financing_options": ["crédito_hipotecario", "leasing"],
        "common_expenses_clp": 95_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-017",
        "name": "Oficina Pequeña Las Condes 30 m²",
        "property_type": "oficina",
        "status": "available",
        "commune": "Las Condes",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Isidora Goyenechea 3000, piso 4, Las Condes",
        "latitude": -33.4178,
        "longitude": -70.5923,
        "price_uf": 3200.0,
        "price_clp": 115_200_000,
        "bedrooms": 0,
        "bathrooms": 1,
        "parking_spots": 1,
        "storage_units": 0,
        "square_meters_total": 32.0,
        "square_meters_useful": 30.0,
        "floor_number": 4,
        "total_floors": 18,
        "orientation": "poniente",
        "year_built": 2018,
        "description": "Oficina compacta en edificio de primera línea de Las Condes. Ideal para consulta médica, estudio jurídico o oficina boutique. Servicio de recepción compartido. 1 estacionamiento incluido.",
        "highlights": "Barrio financiero, recepción compartida, ideal profesionales independientes",
        "amenities": ["recepción_compartida", "sala_espera", "kitchenette_compartida"],
        "nearby_places": [
            {"type": "metro", "name": "Tobalaba", "distance_m": 200},
            {"type": "restaurant", "name": "Food court edificio", "distance_m": 0},
        ],
        "financing_options": ["crédito_hipotecario", "leasing"],
        "common_expenses_clp": 45_000,
        "subsidio_eligible": False,
    },
    # ── Terrenos ──────────────────────────────────────────────────────────────
    {
        "codigo": "SC-018",
        "name": "Terreno 500 m² Buin con Urbanización",
        "property_type": "terreno",
        "status": "available",
        "commune": "Buin",
        "city": "Buin",
        "region": "Región Metropolitana",
        "address": "Camino a Paine km 3, Buin",
        "latitude": -33.7312,
        "longitude": -70.7123,
        "price_uf": 3800.0,
        "price_clp": 136_800_000,
        "bedrooms": None,
        "bathrooms": None,
        "parking_spots": None,
        "storage_units": None,
        "square_meters_total": 500.0,
        "square_meters_useful": 500.0,
        "floor_number": None,
        "total_floors": None,
        "orientation": "norte",
        "year_built": None,
        "description": "Terreno plano totalmente urbanizado en condominio en Buin. Agua, luz y alcantarillado en el sitio. Ideal para construcción de casa. Acceso pavimentado. Posibilidad de subsidio para construcción.",
        "highlights": "Urbanizado, plano, condominio privado, acceso pavimentado",
        "amenities": ["urbanizado", "acceso_pavimentado"],
        "nearby_places": [
            {"type": "supermercado", "name": "Unimarc Buin", "distance_m": 1200},
            {"type": "autopista", "name": "Autopista del Sol", "distance_m": 500},
        ],
        "financing_options": ["crédito_hipotecario", "subsidio_construcción"],
        "common_expenses_clp": 12_000,
        "subsidio_eligible": True,
    },
    {
        "codigo": "SC-019",
        "name": "Terreno 1000 m² Colina Vista Cordillera",
        "property_type": "terreno",
        "status": "available",
        "commune": "Colina",
        "city": "Colina",
        "region": "Región Metropolitana",
        "address": "Av. Chicureo km 8, Colina",
        "latitude": -33.2012,
        "longitude": -70.6634,
        "price_uf": 6500.0,
        "price_clp": 234_000_000,
        "bedrooms": None,
        "bathrooms": None,
        "parking_spots": None,
        "storage_units": None,
        "square_meters_total": 1000.0,
        "square_meters_useful": 1000.0,
        "floor_number": None,
        "total_floors": None,
        "orientation": "norte",
        "year_built": None,
        "description": "Amplio terreno en sector Chicureo con vista a la cordillera. Urbanizado con todos los servicios básicos. Norma permite construcción de casa con piscina. Sector de alto desarrollo y plusvalía.",
        "highlights": "Vista cordillera, 1000 m², Chicureo, alto plusvalía",
        "amenities": ["urbanizado", "vista_cordillera"],
        "nearby_places": [
            {"type": "colegio", "name": "Colegio Los Andes", "distance_m": 800},
            {"type": "mall", "name": "Open Kennedy", "distance_m": 12000},
        ],
        "financing_options": ["crédito_hipotecario"],
        "common_expenses_clp": 25_000,
        "subsidio_eligible": False,
    },
    # ── Propiedades reservadas / vendidas (para variedad de estado) ───────────
    {
        "codigo": "SC-020",
        "name": "Departamento 2D Reservado San Miguel",
        "property_type": "departamento",
        "status": "reserved",
        "commune": "San Miguel",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Departamental 2100, piso 9, San Miguel",
        "latitude": -33.4934,
        "longitude": -70.6512,
        "price_uf": 3100.0,
        "price_clp": 111_600_000,
        "bedrooms": 2,
        "bathrooms": 1,
        "parking_spots": 1,
        "storage_units": 1,
        "square_meters_total": 56.0,
        "square_meters_useful": 51.0,
        "floor_number": 9,
        "total_floors": 12,
        "orientation": "norte",
        "year_built": 2020,
        "description": "Departamento de 2 dormitorios en San Miguel. Actualmente reservado.",
        "highlights": "Reservado — disponibilidad a consultar",
        "amenities": ["piscina", "gimnasio", "bicicletero"],
        "nearby_places": [
            {"type": "metro", "name": "San Miguel", "distance_m": 400},
        ],
        "financing_options": ["crédito_hipotecario"],
        "common_expenses_clp": 48_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-021",
        "name": "Departamento 2D+2B Macul Orientación Norte",
        "property_type": "departamento",
        "status": "available",
        "commune": "Macul",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Vicuña Mackenna 7200, piso 5, Macul",
        "latitude": -33.4889,
        "longitude": -70.5934,
        "price_uf": 3450.0,
        "price_clp": 124_200_000,
        "bedrooms": 2,
        "bathrooms": 2,
        "parking_spots": 1,
        "storage_units": 1,
        "square_meters_total": 68.0,
        "square_meters_useful": 62.0,
        "floor_number": 5,
        "total_floors": 10,
        "orientation": "norte",
        "year_built": 2017,
        "description": "Luminoso departamento en Macul con orientación norte garantizada todo el año. 2 dormitorios amplios con clóset empotrado. Baño principal con tina. Cocina completa con muebles de melamina. Sector con excelente conectividad.",
        "highlights": "Orientación norte, luminoso, 2 baños completos, sector conectado",
        "amenities": ["piscina", "sala_multiuso", "bicicletero", "estacionamiento_visitas"],
        "nearby_places": [
            {"type": "metro", "name": "Macul", "distance_m": 350},
            {"type": "universidad", "name": "U. Católica San Joaquín", "distance_m": 900},
        ],
        "financing_options": ["crédito_hipotecario", "pie_en_cuotas"],
        "common_expenses_clp": 55_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-022",
        "name": "Casa Adosada 3D Condominio Cerrillos",
        "property_type": "casa",
        "status": "available",
        "commune": "Cerrillos",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Pedro Aguirre Cerda 5600, Cerrillos",
        "latitude": -33.4912,
        "longitude": -70.7134,
        "price_uf": 3800.0,
        "price_clp": 136_800_000,
        "bedrooms": 3,
        "bathrooms": 2,
        "parking_spots": 1,
        "storage_units": 0,
        "square_meters_total": 85.0,
        "square_meters_useful": 78.0,
        "floor_number": None,
        "total_floors": 2,
        "orientation": "norte",
        "year_built": 2021,
        "description": "Casa adosada nueva en condominio cerrado Cerrillos. Primer piso: living-comedor abierto, cocina con isla, baño de visitas. Segundo piso: 3 dormitorios y 2 baños. Patio privado. Portería 24/7.",
        "highlights": "Casa nueva, condominio cerrado, patio privado, portería",
        "amenities": ["patio", "portería_24h", "estacionamiento", "área_verde"],
        "nearby_places": [
            {"type": "metro", "name": "Lo Valledor", "distance_m": 1200},
            {"type": "mall", "name": "Arauco Express Cerrillos", "distance_m": 600},
        ],
        "financing_options": ["crédito_hipotecario", "pie_en_cuotas"],
        "common_expenses_clp": 35_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-023",
        "name": "Departamento 2D Recoleta Barrio Patronato",
        "property_type": "departamento",
        "status": "available",
        "commune": "Recoleta",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Recoleta 2300, piso 4, Recoleta",
        "latitude": -33.4156,
        "longitude": -70.6423,
        "price_uf": 2600.0,
        "price_clp": 93_600_000,
        "bedrooms": 2,
        "bathrooms": 1,
        "parking_spots": 0,
        "storage_units": 1,
        "square_meters_total": 50.0,
        "square_meters_useful": 46.0,
        "floor_number": 4,
        "total_floors": 7,
        "orientation": "norte",
        "year_built": 2019,
        "description": "Departamento moderno en el vibrante barrio Patronato, Recoleta. Cerca de bares, restaurantes y vida cultural. Living con balcón pequeño. Buena iluminación natural. Bodega incluida.",
        "highlights": "Barrio Patronato, balcón, bodega, vida cultural",
        "amenities": ["bicicletero", "lavandería_común"],
        "nearby_places": [
            {"type": "metro", "name": "Cerro Blanco", "distance_m": 400},
            {"type": "mercado", "name": "Mercado Tirso de Molina", "distance_m": 700},
        ],
        "financing_options": ["crédito_hipotecario"],
        "common_expenses_clp": 38_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-024",
        "name": "Departamento 1D Inversión Quilín",
        "property_type": "departamento",
        "status": "available",
        "commune": "Macul",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Quilín 3400, piso 7, Macul",
        "latitude": -33.4945,
        "longitude": -70.5712,
        "price_uf": 2100.0,
        "price_clp": 75_600_000,
        "bedrooms": 1,
        "bathrooms": 1,
        "parking_spots": 0,
        "storage_units": 0,
        "square_meters_total": 38.0,
        "square_meters_useful": 35.0,
        "floor_number": 7,
        "total_floors": 14,
        "orientation": "oriente",
        "year_built": 2022,
        "description": "Departamento de inversión en sector Quilín, excelente rentabilidad. Piso alto con buena vista. Edificio con amenidades completas. Actualmente arrendado en $450.000 mensuales (arriendo continúa con nuevo dueño si se desea).",
        "highlights": "Ideal inversión, arrendatario actual, rentabilidad 5%+ anual",
        "amenities": ["piscina", "gimnasio", "roof_garden", "bicicletero"],
        "nearby_places": [
            {"type": "metro", "name": "Quilín", "distance_m": 200},
            {"type": "supermercado", "name": "Lider Quilín", "distance_m": 300},
        ],
        "financing_options": ["crédito_hipotecario"],
        "common_expenses_clp": 42_000,
        "subsidio_eligible": False,
    },
    {
        "codigo": "SC-025",
        "name": "Casa en Condominio Santiago Poniente",
        "property_type": "casa",
        "status": "available",
        "commune": "Quinta Normal",
        "city": "Santiago",
        "region": "Región Metropolitana",
        "address": "Av. Garín 1800, Quinta Normal",
        "latitude": -33.4423,
        "longitude": -70.6989,
        "price_uf": 4600.0,
        "price_clp": 165_600_000,
        "bedrooms": 3,
        "bathrooms": 2,
        "parking_spots": 1,
        "storage_units": 0,
        "square_meters_total": 95.0,
        "square_meters_useful": 87.0,
        "floor_number": None,
        "total_floors": 2,
        "orientation": "norte",
        "year_built": 2018,
        "description": "Casa de dos pisos en condominio privado de Quinta Normal. Living-comedor con piso flotante, cocina equipada. 3 dormitorios en el segundo piso con clósets. Patio con parrilla. Muy bien conectado con el centro.",
        "highlights": "Condominio privado, parrilla, cerca del metro, buena conectividad",
        "amenities": ["patio", "parrilla", "portería", "área_verde"],
        "nearby_places": [
            {"type": "metro", "name": "Quinta Normal", "distance_m": 600},
            {"type": "parque", "name": "Parque Quinta Normal", "distance_m": 500},
            {"type": "supermercado", "name": "Jumbo Garín", "distance_m": 400},
        ],
        "financing_options": ["crédito_hipotecario", "pie_en_cuotas"],
        "common_expenses_clp": 28_000,
        "subsidio_eligible": False,
    },
]

# ──────────────────────────────────────────────────────────────────────────────
# Runner
# ──────────────────────────────────────────────────────────────────────────────

async def main() -> None:
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as session:
        # Find the santiagocentro broker
        result = await session.execute(
            select(Broker).where(Broker.slug == "santiago-centro")
        )
        broker = result.scalars().first()
        if not broker:
            print("❌ Broker 'santiago-centro' not found. Run seed_brokers.py first.")
            return

        print(f"✅ Broker found: {broker.name} (id={broker.id})")

        # Fetch already-seeded internal codes to stay idempotent
        existing_result = await session.execute(
            select(Property.codigo).where(Property.broker_id == broker.id)
        )
        existing_codes = {row for row in existing_result.scalars().all()}

        created = 0
        skipped = 0
        for data in PROPERTIES:
            if data["codigo"] in existing_codes:
                skipped += 1
                continue

            prop = Property(broker_id=broker.id, **data)
            session.add(prop)
            created += 1

        await session.commit()

    await engine.dispose()
    print(f"🏠 Seed completo — creadas: {created}, omitidas (ya existían): {skipped}")


if __name__ == "__main__":
    asyncio.run(main())
