"""change_leads_metadata_to_jsonb

Revision ID: c53002c2955b
Revises: u2p3q4r5s6t7
Create Date: 2026-04-02 10:38:09.385874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53002c2955b'
down_revision: Union[str, None] = 'u2p3q4r5s6t7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Change leads.metadata from JSON to JSONB.
    # JSONB supports native jsonb_set() without manual CASTing,
    # enables GIN indexing, and is more efficient for partial updates.
    op.execute(
        "ALTER TABLE leads ALTER COLUMN metadata TYPE jsonb USING metadata::jsonb"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE leads ALTER COLUMN metadata TYPE json USING metadata::json"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_appointment_google_event', table_name='appointments')
    op.create_index(op.f('ix_appointments_google_event_id'), 'appointments', ['google_event_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.alter_column('broker_chat_configs', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('broker_chat_configs_broker_id_key', 'broker_chat_configs', type_='unique')
    op.drop_index('ix_broker_chat_configs_broker_id', table_name='broker_chat_configs')
    op.create_index(op.f('ix_broker_chat_configs_broker_id'), 'broker_chat_configs', ['broker_id'], unique=True)
    op.create_index(op.f('ix_broker_chat_configs_id'), 'broker_chat_configs', ['id'], unique=False)
    op.drop_constraint('broker_lead_configs_broker_id_key', 'broker_lead_configs', type_='unique')
    op.drop_constraint('broker_prompt_configs_broker_id_key', 'broker_prompt_configs', type_='unique')
    op.drop_constraint('broker_voice_configs_broker_id_key', 'broker_voice_configs', type_='unique')
    op.drop_index('idx_broker_voice_config_broker', table_name='broker_voice_configs')
    op.create_index(op.f('ix_broker_voice_configs_broker_id'), 'broker_voice_configs', ['broker_id'], unique=True)
    op.create_index(op.f('ix_broker_voice_configs_id'), 'broker_voice_configs', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_logs_created_at'), 'campaign_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_broker_id'), 'campaigns', ['broker_id'], unique=False)
    op.alter_column('chat_messages', 'ai_response_used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('chat_messages', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_chat_messages_prompt_version', table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_channel_message_id'), 'chat_messages', ['channel_message_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_prompt_version_id'), 'chat_messages', ['prompt_version_id'], unique=False)
    op.drop_index('idx_knowledge_base_broker_id', table_name='knowledge_base')
    op.create_index(op.f('ix_knowledge_base_broker_id'), 'knowledge_base', ['broker_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.drop_index('idx_leads_assigned_status', table_name='leads')
    op.drop_index('idx_leads_broker_stage', table_name='leads')
    op.create_index(op.f('ix_leads_next_action_at'), 'leads', ['next_action_at'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_stage_entered_at'), 'leads', ['stage_entered_at'], unique=False)
    op.create_index(op.f('ix_message_templates_broker_id'), 'message_templates', ['broker_id'], unique=False)
    op.drop_index('idx_prompt_versions_broker_id', table_name='prompt_versions')
    op.create_index(op.f('ix_prompt_versions_broker_id'), 'prompt_versions', ['broker_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_id'), 'prompt_versions', ['id'], unique=False)
    op.drop_index('idx_messages_lead_created', table_name='telegram_messages')
    op.drop_index('idx_voice_call_external_id', table_name='voice_calls')
    op.create_index('idx_voice_call_external_id', 'voice_calls', ['external_call_id'], unique=False)
    op.create_index(op.f('ix_voice_calls_broker_id'), 'voice_calls', ['broker_id'], unique=False)
    op.create_index(op.f('ix_voice_calls_external_call_id'), 'voice_calls', ['external_call_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_calls_external_call_id'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_broker_id'), table_name='voice_calls')
    op.drop_index('idx_voice_call_external_id', table_name='voice_calls')
    op.create_index('idx_voice_call_external_id', 'voice_calls', ['external_call_id'], unique=False)
    op.create_index('idx_messages_lead_created', 'telegram_messages', ['lead_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_prompt_versions_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_broker_id'), table_name='prompt_versions')
    op.create_index('idx_prompt_versions_broker_id', 'prompt_versions', ['broker_id'], unique=False)
    op.drop_index(op.f('ix_message_templates_broker_id'), table_name='message_templates')
    op.drop_index(op.f('ix_leads_stage_entered_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_next_action_at'), table_name='leads')
    op.create_index('idx_leads_broker_stage', 'leads', ['broker_id', 'pipeline_stage'], unique=False)
    op.create_index('idx_leads_assigned_status', 'leads', ['assigned_to', 'status'], unique=False)
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_broker_id'), table_name='knowledge_base')
    op.create_index('idx_knowledge_base_broker_id', 'knowledge_base', ['broker_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_prompt_version_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_channel_message_id'), table_name='chat_messages')
    op.create_index('idx_chat_messages_prompt_version', 'chat_messages', ['prompt_version_id'], unique=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_messages', 'ai_response_used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_campaigns_broker_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaign_logs_created_at'), table_name='campaign_logs')
    op.drop_index(op.f('ix_broker_voice_configs_id'), table_name='broker_voice_configs')
    op.drop_index(op.f('ix_broker_voice_configs_broker_id'), table_name='broker_voice_configs')
    op.create_index('idx_broker_voice_config_broker', 'broker_voice_configs', ['broker_id'], unique=False)
    op.create_unique_constraint('broker_voice_configs_broker_id_key', 'broker_voice_configs', ['broker_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('broker_prompt_configs_broker_id_key', 'broker_prompt_configs', ['broker_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('broker_lead_configs_broker_id_key', 'broker_lead_configs', ['broker_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_broker_chat_configs_id'), table_name='broker_chat_configs')
    op.drop_index(op.f('ix_broker_chat_configs_broker_id'), table_name='broker_chat_configs')
    op.create_index('ix_broker_chat_configs_broker_id', 'broker_chat_configs', ['broker_id'], unique=False)
    op.create_unique_constraint('broker_chat_configs_broker_id_key', 'broker_chat_configs', ['broker_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('broker_chat_configs', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_appointments_google_event_id'), table_name='appointments')
    op.create_index('idx_appointment_google_event', 'appointments', ['google_event_id'], unique=False)
    # ### end Alembic commands ###

