export { PropertiesPage } from './components/PropertiesPage'
export { PropertyCard } from './components/PropertyCard'
export { PropertyGrid } from './components/PropertyGrid'
export { usePropertiesStore } from './store/propertiesStore'
export { propertiesService } from './services/properties.service'
export type { Property, PropertyStatus, PropertyType, PropertyFilters, CreatePropertyDto, UpdatePropertyDto } from './types'
